USE School

-- WHERE, BETWEEN
-- TODO: IN, LIKE
SELECT *
FROM Schedule
WHERE [Day] BETWEEN 0 AND 4

-- TODO: GROUP BY, COUNT, SUM, AVG, MIN, MAX, AS

-- TODO: HAVING

-- TODO: DISTINCT

-- TODO: ORDER BY, ASC, DESC

-- TODO: TOP, PERCENT, WITH TIES

-- TODO: OFFSET, FETCH, FIRST, ROWS

-- TODO: ROW_NUMBER(), OVER, PARTITION BY

-- TODO: CASE … WHEN … THEN … ELSE …

-- TODO: COALESCE()
